### ISSUE TITLE
Estado de master

### ISSUE THREAD

**Issue by ivanfranco502** [GvGilabert/NetCoreTodoList#2]
@GvGilabert 
El pull request ya figura correctamente. Ahora, si te fijas no quitaste los commits asociados a la funcionalidad de geolocalización.
![image](https://user-images.githubusercontent.com/22622318/49548938-0ec7fa80-f8c6-11e8-864d-800bd214da57.png)

Para esto, debemos parados en el branch `master`, deberías ejecutar lo siguiente:

> git reset --hard ca6a74c2968e622914574a854a7f7eca2604d860

Donde el hash copiado corresponde al commit de Integrations tests fixed. Último commit del TP antes que comenzaras con las modificaciones de Geolocalización.

Y si verificas el status de master, te va a aparecer que diverge. Con lo cual, debemos hacer un git push --force para sobreescribir la historia de master y quede limpio de tu nueva funcionalidad implementada (está toda en el otro branch a la espera de revisar y aprobarla).

**Comment by GvGilabert** [comment]
Bueno prácticamente lo hiciste vos pero quedó, ahora sí el último commit de mi master quedo justo abajo del commit ya squashed de mi branch y además se me fué la advertencia de los conflictos de merging que aparecía.

**Comment by ivanfranco502** [comment]
@GvGilabert jaja, no pasa nada! Lo importante es que vayas familiarizándote con los conceptos. Si ya está todo ok, podes dar por cerrado el issue.
